// Edit this object to update the published portfolio. Browser edits are device-local drafts.
const PORTFOLIO = {
  profile: { name:'Satyam Singh',title:'Social Media Manager / Social Media Executive',location:'Mumbai, India',bio:'Turning brands, ideas and campaigns into engaging digital experiences.',email:'',phone:'',website:'',linkedin:'https://www.linkedin.com/in/satyam-singh77/',instagram:'',other:'',photo:'' },
  intro:{heading:'Good content starts with a better question.',question:'Who are we speaking to—and why should they care?',body:'Turning brands, ideas and campaigns into engaging digital experiences.'},
  skills:['Content Strategy','Social Media Management','Content Creation','Copywriting','Campaign Management','Brand Management','Social Media Marketing','Community Management','Trend Research','Content Calendar','Audience Growth','Analytics & Reporting','Paid Social Media','Influencer Marketing','Creative Direction'].map((name,i)=>({name,category:['Strategy','Management','Creative'][i%3],level:'',evidence:'[ADD A WORK EXAMPLE]'})),
  platforms:['Instagram','Facebook','LinkedIn','YouTube','X','Pinterest','Google Business Profile','Meta Business Suite','Canva','Adobe Creative Cloud','Google Analytics','Meta Ads Manager'].map(name=>({name,experience:'To confirm',notes:'[ADD YOUR EXPERIENCE]'})),
  projects:[
    {name:'[PROJECT 01]',brand:'[CLIENT / BRAND]',platform:'Instagram',type:'Brand campaign',objective:'[CAMPAIGN OBJECTIVE]',role:'[YOUR ROLE]',strategy:'[CONTENT STRATEGY]',approach:'[CONTENT APPROACH]',execution:'[CAMPAIGN EXECUTION]',results:'[VERIFIED RESULTS]',learning:'[KEY LEARNING]',image:'',before:'[BEFORE METRIC]',after:'[AFTER METRIC]'},
    {name:'[PROJECT 02]',brand:'[CLIENT / BRAND]',platform:'LinkedIn',type:'Content strategy',objective:'[CAMPAIGN OBJECTIVE]',role:'[YOUR ROLE]',strategy:'[CONTENT STRATEGY]',approach:'[CONTENT APPROACH]',execution:'[CAMPAIGN EXECUTION]',results:'[VERIFIED RESULTS]',learning:'[KEY LEARNING]',image:'',before:'[BEFORE METRIC]',after:'[AFTER METRIC]'},
    {name:'[PROJECT 03]',brand:'[CLIENT / BRAND]',platform:'YouTube',type:'Video campaign',objective:'[CAMPAIGN OBJECTIVE]',role:'[YOUR ROLE]',strategy:'[CONTENT STRATEGY]',approach:'[CONTENT APPROACH]',execution:'[CAMPAIGN EXECUTION]',results:'[VERIFIED RESULTS]',learning:'[KEY LEARNING]',image:'',before:'[BEFORE METRIC]',after:'[AFTER METRIC]'}
  ],
  content:['Instagram post','Reel','Story','LinkedIn post','Campaign creative','Brand campaign','Promotional graphic','Video thumbnail'].map((type,i)=>({title:'[CONTENT '+String(i+1).padStart(2,'0')+']',type,platform:['Instagram','Instagram','Instagram','LinkedIn','Instagram','Facebook','Pinterest','YouTube'][i],campaign:i%3,objective:'[OBJECTIVE]',reach:'[REACH]',engagement:'[ENGAGEMENT]',contribution:'[MY CONTRIBUTION]',image:'',link:''})),
  metrics:[{label:'Monthly reach',value:'XXXK'},{label:'Engagement growth',value:'+XX%'},{label:'Engagement rate',value:'XX%'},{label:'Follower growth',value:'+XX'},{label:'Impressions',value:'XXXK'},{label:'Content published',value:'XX'},{label:'Campaigns managed',value:'XX+'},{label:'Leads generated',value:'XX'}],
  journey:[{company:'IDSSPL Technologies Pvt. Ltd',role:'[ROLE TO CONFIRM]',duration:'[DURATION]',responsibilities:'[RESPONSIBILITIES]',campaigns:'[CAMPAIGNS HANDLED]',platforms:'[PLATFORMS MANAGED]',achievements:'[VERIFIED ACHIEVEMENTS]'},{company:'[COMPANY]',role:'[YOUR ROLE]',duration:'[DURATION]',responsibilities:'[RESPONSIBILITIES]',campaigns:'[CAMPAIGNS HANDLED]',platforms:'[PLATFORMS MANAGED]',achievements:'[VERIFIED ACHIEVEMENTS]'}],
  philosophy:[{title:'Strategy',text:'Every piece of content has a purpose.'},{title:'Creativity',text:'Ideas should stop the scroll.'},{title:'Data',text:'Performance should guide decisions.'},{title:'Trends',text:'Stay relevant without blindly following trends.'},{title:'Consistency',text:'Strong brands are built continuously.'},{title:'Community',text:'Social media is about people, not just posts.'}],
  sources:[{label:'LinkedIn public profile — name, location, social media background and company listing',url:'https://www.linkedin.com/in/satyam-singh77/'}]
};

export default PORTFOLIO;
